apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-base.fullname" . }}
  labels: {{- include "app-base.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "app-base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "app-base.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
